Areas/Admin/Controllers/productsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Duc_BTL.Areas.Admin.Models;
using Duc_BTL.Data;

namespace Duc_BTL.Areas.Admin.Controllers
{
  [Area("Admin")]
  public class productsController : Controller
  {
    private readonly Duc_BTLContext _context;
    private readonly IWebHostEnvironment _hostingEnvironment;


    public productsController(Duc_BTLContext context, IWebHostEnvironment hostingEnvironment)
    {
      _context = context;
      _hostingEnvironment = hostingEnvironment;
    }

    // GET: Admin/products
    public async Task<IActionResult> Index()
    {
      var Duc_BTLContext = _context.product.Include(p => p.category);
      return View(await Duc_BTLContext.ToListAsync());
    }

    // GET: Admin/products/Details/5
    public async Task<IActionResult> Details(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var product = await _context.product
          .Include(p => p.category)
          .FirstOrDefaultAsync(m => m.Id == id);
      if (product == null)
      {
        return NotFound();
      }
      ViewBag.CategoryId = new SelectList(_context.category, "Id", "Name");
      return View(product);
    }

    // GET: Admin/products/Create
    public IActionResult Create()
    {
      ViewData["CategoryId"] = new SelectList(_context.category, "Id", "Name");
      return View();
    }

    // POST: Admin/products/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Name,Description,Image,Price,Quantity,CategoryId")] product product, IFormFile? fileInput)
    {
      if (ModelState.IsValid)
      {
        if (fileInput != null)
        {
					var extension = Path.GetExtension(fileInput.FileName);
					var fileName = Guid.NewGuid().ToString().Substring(0, 10 - extension.Length) + extension;
					var filePath = Path.Combine(_hostingEnvironment.WebRootPath, "assets", "img", fileName);
					var fileOld = Path.Combine(_hostingEnvironment.WebRootPath, "assets", "img", fileInput.FileName);
					// Kiểm tra xem tệp có tồn tại trong thư mục Image hay không
					if (System.IO.File.Exists(fileOld))
					{
						// Nếu tệp đã tồn tại, không cần tạo tên mới
						product.Image = fileInput.FileName;
					}
					else
					{
						// Nếu tệp không tồn tại, tạo một tên file mới và lưu tệp vào thư mục
						using (var stream = new FileStream(filePath, FileMode.Create))
						{
							await fileInput.CopyToAsync(stream);
						}
            // Lưu đường dẫn của tệp vào model
            product.Image = fileName;
					}
				}
        _context.Add(product);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
      }
      ViewData["CategoryId"] = new SelectList(_context.category, "Id", "Name", product.CategoryId);
      return View(product);
    }

    // GET: Admin/products/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var product = await _context.product.FindAsync(id);
      if (product == null)
      {
        return NotFound();
      }
      ViewData["CategoryId"] = new SelectList(_context.category, "Id", "Name", product.CategoryId);
      return View(product);
    }

    // POST: Admin/products/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Image,Price,Quantity,CategoryId")] product product, IFormFile? fileInput)
    {
      if (id != product.Id)
      {
        return NotFound();
      }

      if (ModelState.IsValid)
      {
        try
        {
          
					if (fileInput != null)
					{
            product.Image = "";
						var extension = Path.GetExtension(fileInput.FileName);
						var fileName = Guid.NewGuid().ToString().Substring(0, 10 - extension.Length) + extension;
						var filePath = Path.Combine(_hostingEnvironment.WebRootPath, "assets", "img", fileName);
						var fileOld = Path.Combine(_hostingEnvironment.WebRootPath, "assets", "img", fileInput.FileName);
						// Kiểm tra xem tệp có tồn tại trong thư mục Image hay không
						if (System.IO.File.Exists(fileOld))
						{
							// Nếu tệp đã tồn tại, không cần tạo tên mới
							product.Image = fileInput.FileName;
						}
						else
						{
							// Nếu tệp không tồn tại, tạo một tên file mới và lưu tệp vào thư mục
							using (var stream = new FileStream(filePath, FileMode.Create))
							{
								await fileInput.CopyToAsync(stream);
							}
							// Lưu đường dẫn của tệp vào model
							product.Image = fileName;
						}
					}
					_context.Update(product);
          await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
          if (!productExists(product.Id))
          {
            return NotFound();
          }
          else
          {
            throw;
          }
        }
        return RedirectToAction(nameof(Index));
      }
      ViewData["CategoryId"] = new SelectList(_context.category, "Id", "Name", product.CategoryId);
      return View(product);
    }

    // GET: Admin/products/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var product = await _context.product
          .Include(p => p.category)
          .FirstOrDefaultAsync(m => m.Id == id);
      if (product == null)
      {
        return NotFound();
      }
      ViewData["CategoryId"] = new SelectList(_context.category, "Id", "Name");
      return View(product);
    }

    // POST: Admin/products/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
      var product = await _context.product.FindAsync(id);
      if (product != null)
      {
        _context.product.Remove(product);
      }

      await _context.SaveChangesAsync();
      return RedirectToAction(nameof(Index));
    }

    private bool productExists(int id)
    {
      return _context.product.Any(e => e.Id == id);
    }
  }
}

Views/Shared/_HeaderPartialView.cshtml
@using System.Security.Claims
@inject Duc_BTL.Controllers.ICartService _cartService;
@{
	int count = 0;
	if (User.Identity.IsAuthenticated)
	{
		int userId = int.Parse(User.FindFirstValue("Id"));
		count = _cartService.getCartCountByUserId(userId);
	}
}

<div class="top-header-area" id="sticker">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 col-sm-12 text-center">
				<div class="main-menu-wrap">
					<!-- logo -->
					<div class="site-logo">
						<a href="/">
							<img src="~/assets/img/logo.png" alt="">
						</a>
					</div>
					<!-- logo -->
					<!-- menu start -->
					<nav class="main-menu">
						<ul>
              <li class="current-list-item"><a href="/">Home</a></li>
              <li><a href="/products/shop">Shop</a></li>
							<li><a href="/home/news">News</a></li>
							<li><a href="/home/contact">Contact</a></li>
							<li>
								<span class="header-icons">
									<a class="shopping-cart" href="/shopping/shoppingcart">
										<i class="fas fa-shopping-cart">
											<sup style="font-size: 15px; padding: 8px;">@count</sup>
										</i>
									</a>
									<a class="mobile-hide search-bar-icon" href="#"><i class="fas fa-search"></i></a>
								</span>
								<span>
									@if (User.Identity.IsAuthenticated)
									{
										<a href="/user/logout">Đăng xuất</a>
									}
									else
									{
										<a href="/user/login">Đăng nhập</a>
									}
								</span>
							</li>
						</ul>
					</nav>
					<a class="mobile-show search-bar-icon" href="#"><i class="fas fa-search"></i></a>
					<div class="mobile-menu"></div>
					<!-- menu end -->
				</div>
			</div>
		</div>
	</div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Responsive Bootstrap4 Shop Template, Created by Imran Hossain from https://imransdesign.com/">

	<!-- title -->
	<title>Fruitkha - Slider Version</title>

	<!-- favicon -->
	<link rel="shortcut icon" type="image/png" href="~/assets/img/favicon.png">
	<!-- google font -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
	<!-- fontawesome -->
	<link rel="stylesheet" href="~/assets/css/all.min.css">
	<!-- bootstrap -->
	<link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap.min.css">
	<!-- owl carousel -->
	<link rel="stylesheet" href="~/assets/css/owl.carousel.css">
	<!-- magnific popup -->
	<link rel="stylesheet" href="~/assets/css/magnific-popup.css">
	<!-- animate css -->
	<link rel="stylesheet" href="~/assets/css/animate.css">
	<!-- mean menu css -->
	<link rel="stylesheet" href="~/assets/css/meanmenu.min.css">
	<!-- main style -->
	<link rel="stylesheet" href="~/assets/css/main.css">
	<!-- responsive -->
	<link rel="stylesheet" href="~/assets/css/responsive.css">

</head>
<body>

	<!--PreLoader-->
	<div class="loader">
		<div class="loader-inner">
			<div class="circle"></div>
		</div>
	</div>
	<!--PreLoader Ends-->
	<!-- header -->
	@await Html.PartialAsync("_HeaderPartialView")
	<!-- end header -->
	<!-- search area -->
	<div class="search-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<span class="close-btn"><i class="fas fa-window-close"></i></span>
					<div class="search-bar">
						<form asp-controller="products" asp-action="shop" class="search-bar-tablecell">
							<h3>Search For:</h3>
							<input type="text" placeholder="Keywords" name="keywords">
							<button type="submit">Search <i class="fas fa-search"></i></button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end search area -->
	@RenderBody()
	<!-- logo carousel -->
	<div class="logo-carousel-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="logo-carousel-inner">
						<div class="single-logo-item">
							<img src="~/assets/img/company-logos/1.png" alt="">
						</div>
						<div class="single-logo-item">
							<img src="~/assets/img/company-logos/2.png" alt="">
						</div>
						<div class="single-logo-item">
							<img src="~/assets/img/company-logos/3.png" alt="">
						</div>
						<div class="single-logo-item">
							<img src="~/assets/img/company-logos/4.png" alt="">
						</div>
						<div class="single-logo-item">
							<img src="~/assets/img/company-logos/5.png" alt="">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end logo carousel -->
	<!-- footer -->
	<div class="footer-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-6">
					<div class="footer-box about-widget">
						<h2 class="widget-title">About us</h2>
						<p>Ut enim ad minim veniam perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae.</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box get-in-touch">
						<h2 class="widget-title">Get in Touch</h2>
						<ul>
							<li>34/8, East Hukupara, Gifirtok, Sadan.</li>
							<li>support@fruitkha.com</li>
							<li>+00 111 222 3333</li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box pages">
						<h2 class="widget-title">Pages</h2>
						<ul>
							<li><a href="index.html">Home</a></li>
							<li><a href="about.html">About</a></li>
							<li><a href="services.html">Shop</a></li>
							<li><a href="news.html">News</a></li>
							<li><a href="contact.html">Contact</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box subscribe">
						<h2 class="widget-title">Subscribe</h2>
						<p>Subscribe to our mailing list to get the latest updates.</p>
						<form action="index.html">
							<input type="email" placeholder="Email">
							<button type="submit"><i class="fas fa-paper-plane"></i></button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end footer -->
	<!-- copyright -->
	<div class="copyright">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-12">
					<p>
						Copyrights &copy; 2019 - <a href="https://imransdesign.com/">Imran Hossain</a>,  All Rights Reserved.<br>
						Distributed By - <a href="https://themewagon.com/">Themewagon</a>
					</p>
				</div>
				<div class="col-lg-6 text-right col-md-12">
					<div class="social-icons">
						<ul>
							<li><a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-linkedin"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-dribbble"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end copyright -->

	

	<!-- jquery -->
	<script src="~/assets/js/jquery-1.11.3.min.js"></script>
	<!-- bootstrap -->
	<script src="~/assets/bootstrap/js/bootstrap.min.js"></script>
	<!-- count down -->
	<script src="~/assets/js/jquery.countdown.js"></script>
	<!-- isotope -->
	<script src="~/assets/js/jquery.isotope-3.0.6.min.js"></script>
	<!-- waypoints -->
	<script src="~/assets/js/waypoints.js"></script>
	<!-- owl carousel -->
	<script src="~/assets/js/owl.carousel.min.js"></script>
	<!-- magnific popup -->
	<script src="~/assets/js/jquery.magnific-popup.min.js"></script>
	<!-- mean menu -->
	<script src="~/assets/js/jquery.meanmenu.min.js"></script>
	<!-- sticker js -->
	<script src="~/assets/js/sticker.js"></script>
	<!-- main js -->
	<script src="~/assets/js/main.js"></script>

	<script>
		// Thêm sản phẩm vào giỏ hàng
		$(document).on('click', '.js_btnAddToCart', function () {
			var productId = this.getAttribute('data-productId');
			$.ajax({
				type: "GET",
				dataType: "JSON",
				url: "/shopping/addtocart",
				data: { productIdOrder: productId, quantity: 1 },
				success: function (rs) {
					window.location.href = rs.url;
				}
			})
		})

		// thêm giỏ hàng trang chi tiết
		$(document).on('click', '.btn_addtocartDatails', function () {
			let quantity = $('.productInfo__addToCart .input-qty').val();
			let productId = this.getAttribute('data-productId');
			console.log(quantity)
			if (parseInt(quantity) > 0) {
				$.ajax({
					type: "GET",
					dataType: "JSON",
					url: "/shopping/addtocart",
					data: { productIdOrder: productId, quantity: quantity },
					success: function (rs) {
						window.location.href = rs.url;
					}
				})
			}
		});

		// // cập nhật giỏ hàng
		// $(document).on('click', '.buttons_added .btn-updateQty', function () {
		// 	let parent = this.closest('.buttons_added');
		// 	let cartId = parent.getAttribute('data-cartId')
		// 	if ($(this).hasClass('minus')) {
		// 		$.ajax({
		// 			type: "POST",
		// 			dataType: "JSON",
		// 			url: "/shopping/updatecart",
		// 			data: { cartId: cartId, quantity: -1 },
		// 			success: function (rs) {
		// 				window.location.href = rs.url;
		// 			}
		// 		});
		// 	} else {
		// 		$.ajax({
		// 			type: "POST",
		// 			url: "/shopping/updatecart",
		// 			data: { cartId: cartId, quantity: 1 },
		// 			success: function (rs) {
		// 				window.location.href = rs.url;
		// 			}
		// 		});
		// 	}
		// });


	</script>

	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>