Areas/Admin/Models/user.cs
namespace Duc_BTL.Areas.Admin.Models
{
	public class user
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public string Email { get; set; }
		public string Password { get; set; }
		public string Role { get; set; }
	}
}

Areas/Admin/Controllers/usersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Duc_BTL.Areas.Admin.Models;
using Duc_BTL.Data;

namespace Duc_BTL.Areas.Admin.Controllers
{
  [Area("Admin")]
  public class usersController : Controller
  {
    private readonly Duc_BTLContext _context;

    public usersController(Duc_BTLContext context)
    {
      _context = context;
    }

    // GET: Admin/users
    public async Task<IActionResult> Index()
    {
      return View(await _context.user.ToListAsync());
    }

    // GET: Admin/users/Details/5
    public async Task<IActionResult> Details(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var user = await _context.user
          .FirstOrDefaultAsync(m => m.Id == id);
      if (user == null)
      {
        return NotFound();
      }
      var roles = new List<SelectListItem>
      {
        new SelectListItem { Value = "QTV", Text = "Quản trị viên"},
        new SelectListItem { Value = "NV", Text = "Nhân viên"},
        new SelectListItem { Value = "KH", Text = "Khách hàng"}
      };
      ViewBag.Roles = roles;
      return View(user);
    }

    // GET: Admin/users/Create
    public IActionResult Create()
    {
      var roles = new List<SelectListItem>
      {
        new SelectListItem { Value = "QTV", Text = "Quản trị viên"},
        new SelectListItem { Value = "NV", Text = "Nhân viên"},
        new SelectListItem { Value = "KH", Text = "Khách hàng"}
      };
      ViewBag.Roles = roles;
      return View();
    }

    // POST: Admin/users/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Name,Email,Password,Role,Phone,Address")] user user)
    {
      if (ModelState.IsValid)
      {
        _context.Add(user);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
      }
      var roles = new List<SelectListItem>
      {
        new SelectListItem { Value = "QTV", Text = "Quản trị viên"},
        new SelectListItem { Value = "NV", Text = "Nhân viên"},
        new SelectListItem { Value = "KH", Text = "Khách hàng"}
      };
      ViewBag.Roles = roles;
      return View(user);
    }

    // GET: Admin/users/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var user = await _context.user.FindAsync(id);
      if (user == null)
      {
        return NotFound();
      }
      var roles = new List<SelectListItem>
      {
        new SelectListItem { Value = "QTV", Text = "Quản trị viên"},
        new SelectListItem { Value = "NV", Text = "Nhân viên"},
        new SelectListItem { Value = "KH", Text = "Khách hàng"}
      };
      ViewBag.Roles = roles;
      return View(user);
    }

    // POST: Admin/users/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Email,Password,Role,Phone,Address")] user user)
    {
      if (id != user.Id)
      {
        return NotFound();
      }

      if (ModelState.IsValid)
      {
        try
        {
          _context.Update(user);
          await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
          if (!userExists(user.Id))
          {
            return NotFound();
          }
          else
          {
            throw;
          }
        }
        return RedirectToAction(nameof(Index));
      }
      var roles = new List<SelectListItem>
      {
        new SelectListItem { Value = "QTV", Text = "Quản trị viên"},
        new SelectListItem { Value = "NV", Text = "Nhân viên"},
        new SelectListItem { Value = "KH", Text = "Khách hàng"}
      };
      ViewBag.Roles = roles;
      return View(user);
    }

    // GET: Admin/users/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var user = await _context.user
          .FirstOrDefaultAsync(m => m.Id == id);
      if (user == null)
      {
        return NotFound();
      }
      var roles = new List<SelectListItem>
      {
        new SelectListItem { Value = "QTV", Text = "Quản trị viên"},
        new SelectListItem { Value = "NV", Text = "Nhân viên"},
        new SelectListItem { Value = "KH", Text = "Khách hàng"}
      };
      ViewBag.Roles = roles;
      return View(user);
    }

    // POST: Admin/users/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
      var user = await _context.user.FindAsync(id);
      if (user != null)
      {
        _context.user.Remove(user);
      }

      await _context.SaveChangesAsync();
      return RedirectToAction(nameof(Index));
    }

    private bool userExists(int id)
    {
      return _context.user.Any(e => e.Id == id);
    }
  }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Duc_BTL.Areas.Admin.Models;
using System.Net.Mail;
using System.Net;
using System.Security.Claims;
using Duc_BTL.Data;
using Humanizer.Localisation.NumberToWords;
using Microsoft.AspNetCore.Http.Extensions;

namespace Duc_BTL.Controllers
{
  public interface IUserService
  {
    public user getUserByUserId(int userId);
  }
  public class UserController : Controller, IUserService
  {
    private readonly Duc_BTLContext _context;

    public UserController(Duc_BTLContext context)
    {
      _context = context;
    }
    public IActionResult MyAccount ()
    {
      if (User.Identity.IsAuthenticated)
      {
        int userId = int.Parse(User.FindFirstValue("Id"));
        user us = _context.user.FirstOrDefault(x => x.Id == userId);
        return View(us);
      }
      return Redirect("/user/login");
    }
    public IActionResult Edit (int? id)
    {
      var user = _context.user.FirstOrDefault(x => x.Id == id);
      return View(user);
    }

    [HttpPost]
    public IActionResult Edit(int id, string name, string email, string phone, string address)
    {
      var user = _context.user.FirstOrDefault(x => x.Id == id);
      user.Name = name;
      user.Email = email;
      _context.Update(user);
      _context.SaveChanges();
      return Redirect("/user/myaccount");
    }

    public IActionResult Login()
    {
      return View();
    }

    [HttpPost]
    public IActionResult Login(string email, string password)
    {
      var user = _context.user.Where(x => x.Email == email && x.Password == password).FirstOrDefault();
      if (user != null)
      {
        var claims = new List<Claim>
        {
            new Claim("Id", user.Id.ToString()),
            new Claim(ClaimTypes.Email, user.Email),
            new Claim(ClaimTypes.Role, user.Role),
        };

        var claimsIdentity = new ClaimsIdentity(
            claims, CookieAuthenticationDefaults.AuthenticationScheme);

        HttpContext.SignInAsync(
            CookieAuthenticationDefaults.AuthenticationScheme,
            new ClaimsPrincipal(claimsIdentity));
        return Redirect("/");

      }
      string message = "Tài khoản, mật khẩu không hợp lệ!";
      ViewBag.Message = message;
      return View();
    }

    public IActionResult LogOut()
    {
      HttpContext.SignOutAsync(
      CookieAuthenticationDefaults.AuthenticationScheme);
      return Redirect("/");
    }
    public IActionResult Register ()
    {
      return View();
    }

    [HttpPost]
    public IActionResult Register(string name, string email, string password, string repassword)
    {
      var user = _context.user.Where(u => u.Email == email).FirstOrDefault();
      bool checkEmail = user == null; // true neu chua ton tai email
      if (ModelState.IsValid && password == repassword && checkEmail)
      {
        user us = new user
        {
          Name = name,
          Email = email,
          Password = password,
          Role = "KH"
        };
        _context.Add(us);
        _context.SaveChanges();
        ViewBag.Message = "Đăng ký thành công!";
        ViewBag.Status = true;
        return Redirect("/user/login"); 
      }
      ViewBag.Status = false;
      if (checkEmail == false)
      {
        ViewBag.Message = "Email này đã đăng ký tài khoản vui lòng thử lại!";
      }
      else
      {
        ViewBag.Message = "Vui lòng nhập mật khẩu trùng nhau!";
      }
      if (ViewBag.Status == false)
      {
        return View();
      }
      else
      {
        return Redirect("/user/login");
      }
    }

    public user getUserByUserId(int userId)
    {
      user us = _context.user.FirstOrDefault(x => x.Id == userId);
      return us;
    }
  }
}

Areas/Admin/Views/users/Create.cshtml
@model Duc_BTL.Areas.Admin.Models.user

@{
    ViewData["Title"] = "Thêm mới người dùng";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Thêm mới người dùng</h1>
<hr />
<div class="row">
  <div class="col-md-4">
    <form asp-action="create">
      <div asp-validation-summary="ModelOnly" class="text-danger"></div>
      <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input type="text" asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="Email" class="control-label"></label>
        <input type="email" asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="Password" class="control-label"></label>
        <input type="password" asp-for="Password" class="form-control" />
        <span asp-validation-for="Password" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="Role" class="control-label"></label>
        <select class="form-control" asp-for="Role" asp-items="ViewBag.Roles"></select>
        <span asp-validation-for="Role" class="text-danger"></span>
      </div>

      <div class="form-group">
        <button type="submit" class="btn btn-primary mr-2">Thêm mới</button>
        <a href="/admin/users" class="btn btn-outline-danger">Trở lại</a>
      </div>
    </form>
  </div>
</div>

Areas/Admin/Views/users/Delete.cshtml
@model Duc_BTL.Areas.Admin.Models.user

@{
  ViewData["Title"] = "Xóa người dùng";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="card mb-4">
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Xóa người dùng</h6>
  </div>
  <div class="card-body">
    <form asp-controller="users" asp-action="delete">

      <div class="form-group row">
        <label asp-for="Id" class="col-sm-1 control-label">ID</label>
        <div class="col-sm-3">
          <input type="text" asp-for="Id" class="form-control" readonly/>
          <span asp-validation-for="Id" class="text-danger"></span>
        </div>
      </div>
      <div class="form-group row">
        <label asp-for="Name" class="col-sm-1 control-label">Name</label>
        <div class="col-sm-3">
          <input type="text" asp-for="Name" class="form-control" />
          <span asp-validation-for="Name" class="text-danger"></span>
        </div>
      </div>
      <div class="form-group row">
        <label asp-for="Email" class="col-sm-1 control-label">Email</label>
        <div class="col-sm-3">
          <input type="email" asp-for="Email" class="form-control" />
          <span asp-validation-for="Email" class="text-danger"></span>
        </div>
      </div>
      <div class="form-group row">
        <label asp-for="Password" class="col-sm-1 control-label">Password</label>
        <div class="col-sm-3">
          <input type="password" asp-for="Password" class="form-control" />
          <span asp-validation-for="Password" class="text-danger"></span>
        </div>
      </div>
      <div class="form-group row">
        <label asp-for="Role" class="col-sm-1 control-label">Role</label>
        <div class="col-sm-3">
          <select class="form-control" asp-for="Role" asp-items="ViewBag.Roles"></select>
          <span asp-validation-for="Role" class="text-danger"></span>
        </div>
      </div>
      <button type="submit" class="btn btn-outline-primary mr-2">Xóa</button>
      <a href="/admin/users" class="btn btn-outline-danger">Trở lại</a>
    </form>
  </div>
</div>

Areas/Admin/Views/users/Details.cshtml
@model Duc_BTL.Areas.Admin.Models.user

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="card mb-4">
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Chỉnh sửa thông tin người dùng</h6>
  </div>
  <div class="card-body">
    <form>

      <div class="form-group row">
        <label asp-for="Id" class="col-sm-1 control-label">ID</label>
        <div class="col-sm-3">
          <input type="text" asp-for="Id" class="form-control" readonly />
          <span asp-validation-for="Id" class="text-danger"></span>
        </div>
      </div>
      <div class="form-group row">
        <label asp-for="Name" class="col-sm-1 control-label">Name</label>
        <div class="col-sm-3">
          <input type="text" asp-for="Name" class="form-control" readonly />
          <span asp-validation-for="Name" class="text-danger"></span>
        </div>
      </div>
      <div class="form-group row">
        <label asp-for="Email" class="col-sm-1 control-label">Email</label>
        <div class="col-sm-3">
          <input type="email" asp-for="Email" class="form-control" readonly />
          <span asp-validation-for="Email" class="text-danger"></span>
        </div>
      </div>
      <div class="form-group row">
        <label asp-for="Password" class="col-sm-1 control-label">Password</label>
        <div class="col-sm-3">
          <input type="password" asp-for="Password" class="form-control" readonly />
          <span asp-validation-for="Password" class="text-danger"></span>
        </div>
      </div>
      <div class="form-group row">
        <label asp-for="Role" class="col-sm-1 control-label">Role</label>
        <div class="col-sm-3">
          <select class="form-control" asp-for="Role" asp-items="ViewBag.Roles"></select>
          <span asp-validation-for="Role" class="text-danger"></span>
        </div>
      </div>
      <a href="/admin/users/edit?id=@Model.Id" class="btn btn-outline-primary mr-2">Sửa</a>
      <a href="/admin/users" class="btn btn-outline-danger">Trở lại</a>
    </form>
  </div>
</div>

Areas/Admin/Views/users/Edit.cshtml
@model Duc_BTL.Areas.Admin.Models.user

@{
    ViewData["Title"] = "Chỉnh sửa thông tin người dùng";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="card mb-4">
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Chỉnh sửa thông tin người dùng</h6>
  </div>
  <div class="card-body">
    <form asp-controller="users" asp-action="edit">

      <div class="form-group row">
        <label asp-for="Id" class="col-sm-1 control-label">ID</label>
        <div class="col-sm-3">
          <input type="text" asp-for="Id" class="form-control" readonly />
          <span asp-validation-for="Id" class="text-danger"></span>
        </div>
      </div>
      <div class="form-group row">
        <label asp-for="Name" class="col-sm-1 control-label">Name</label>
        <div class="col-sm-3">
          <input type="text" asp-for="Name" class="form-control" />
          <span asp-validation-for="Name" class="text-danger"></span>
        </div>
      </div>
      <div class="form-group row">
        <label asp-for="Email" class="col-sm-1 control-label">Email</label>
        <div class="col-sm-3">
          <input type="email" asp-for="Email" class="form-control" />
          <span asp-validation-for="Email" class="text-danger"></span>
        </div>
      </div>
      <div class="form-group row">
        <label asp-for="Password" class="col-sm-1 control-label">Password</label>
        <div class="col-sm-3">
          <input type="password" asp-for="Password" class="form-control" />
          <span asp-validation-for="Password" class="text-danger"></span>
        </div>
      </div>
      <div class="form-group row">
        <label asp-for="Role" class="col-sm-1 control-label">Role</label>
        <div class="col-sm-3">
          <select class="form-control" asp-for="Role" asp-items="ViewBag.Roles"></select>
          <span asp-validation-for="Role" class="text-danger"></span>
        </div>
      </div>
      <button type="submit" class="btn btn-outline-primary mr-2">Cập nhật</button>
      <a href="/admin/users" class="btn btn-outline-danger">Trở lại</a>
    </form>
  </div>
</div>

Areas/Admin/Views/users/Index.cshtml
@model IEnumerable<Duc_BTL.Areas.Admin.Models.user>

@{
    ViewData["Title"] = "Danh sách người dùng";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
  <div class="col-lg-9 mb-4">
    <!-- Simple Tables -->
    <div class="card">
      <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Danh sách người dùng</h6>
      </div>
      <div class="table-responsive">
        <table class="table align-items-center table-flush">
          <thead class="thead-light">
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Email</th>
              <th>Role</th>
              <th>#</th>
            </tr>
          </thead>
          <tbody>
            @foreach (var item in Model)
            {
              <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Email</td>
                <td>@item.Role</td>
                <td>
                  <a href="/admin/users/edit?id=@item.Id" class="btn btn-outline-primary">Sửa</a>
                  <a href="/admin/users/details?id=@item.Id" class="btn btn-outline-info">Chi tiết</a>
                  <a href="/admin/users/delete?id=@item.Id" class="btn btn-outline-danger">Xóa</a>
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<a href="/admin/users/create" class="btn btn-outline-primary mb-5">Thêm mới</a>