Areas/Admin/Models/category.cs
namespace Duc_BTL.Areas.Admin.Models
{
	public class category
	{
		public int Id { get; set; }
		public string Name { get; set; }
	}
}

Areas/Admin/Controllers/categoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting.Internal;
using Duc_BTL.Areas.Admin.Models;
using Duc_BTL.Data;

namespace Duc_BTL.Areas.Admin.Controllers
{
  [Area("Admin")]
  public class categoriesController : Controller
  {
    private readonly Duc_BTLContext _context;
    private readonly IWebHostEnvironment _hostingEnvironment;

    public categoriesController(Duc_BTLContext context, IWebHostEnvironment hostingEnvironment)
    {
      _context = context;
      _hostingEnvironment = hostingEnvironment;
    }

    // GET: Admin/categories
    public async Task<IActionResult> Index()
    {
      return View(await _context.category.ToListAsync());
    }

    // GET: Admin/categories/Details/5
    public async Task<IActionResult> Details(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var category = await _context.category
          .FirstOrDefaultAsync(m => m.Id == id);
      if (category == null)
      {
        return NotFound();
      }

      return View(category);
    }

    // GET: Admin/categories/Create
    public IActionResult Create()
    {
      return View();
    }

    // POST: Admin/categories/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Name")] category category)
    {
      if (ModelState.IsValid)
      {
        _context.Add(category);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
      }
      return View(category);
    }

    // GET: Admin/categories/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var category = await _context.category.FindAsync(id);
      if (category == null)
      {
        return NotFound();
      }
      return View(category);
    }

    // POST: Admin/categories/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] category category)
    {
      if (id != category.Id)
      {
        return NotFound();
      }

      if (ModelState.IsValid)
      {
        try
        {
          
          _context.Update(category);
          await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
          if (!categoryExists(category.Id))
          {
            return NotFound();
          }
          else
          {
            throw;
          }
        }
        return RedirectToAction(nameof(Index));
      }
      return View(category);
    }

    // GET: Admin/categories/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var category = await _context.category
          .FirstOrDefaultAsync(m => m.Id == id);
      if (category == null)
      {
        return NotFound();
      }

      return View(category);
    }

    // POST: Admin/categories/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
      var category = await _context.category.FindAsync(id);
      if (category != null)
      {
        _context.category.Remove(category);
      }

      await _context.SaveChangesAsync();
      return RedirectToAction(nameof(Index));
    }

    private bool categoryExists(int id)
    {
      return _context.category.Any(e => e.Id == id);
    }
  }
}

Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Duc_BTL.Areas.Admin.Models;
using Duc_BTL.Data;

namespace Duc_BTL.Controllers
{
  public interface ICategoryService
  {
    public int getProductCountByCateId (int cateId);
    public List<category> getListCategory();
    public List<SelectListItem> getSelectListCategory();
    public int getCateIdByCateName(string cateName);
  }
  public class CategoryController : Controller, ICategoryService
  {
    private readonly Duc_BTLContext _context;

    public CategoryController(Duc_BTLContext context)
    {
      _context = context;
    }
    public IActionResult Index()
    {
      return View();
    }
    public int getProductCountByCateId(int cateId)
    {
      int count = _context.product.Where(x => x.CategoryId == cateId).Count();
      return count;
    }
    public List<category> getListCategory()
    {
      var list = _context.category.ToList();
      return list;
    }

    public List<SelectListItem> getSelectListCategory ()
    {
      var list = _context.category.ToList();
      List<SelectListItem> rs = new List<SelectListItem>();
      foreach (var item in list)
      {
        rs.Add(new SelectListItem { Value = item.Id.ToString(), Text = item.Name });
      }
      return rs;
    }
    public int getCateIdByCateName(string cateName)
    {
      var obj = _context.category.FirstOrDefault(x => x.Name == cateName);
      if (obj == null)
        return 0;
      return obj.Id;
    }
  }
}

Areas/Admin/Views/categories/Create.cshtml
@model Duc_BTL.Areas.Admin.Models.category

@{
  ViewData["Title"] = "Thêm mới danh mục";
  Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Thêm mới danh mục</h1>
<hr />
<div class="row">
  <div class="col-md-4">
    <form asp-action="Create">
      <div asp-validation-summary="ModelOnly" class="text-danger"></div>
      <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-primary mr-2">Tạo mới</button>
        <a asp-action="Index" class="btn btn-outline-danger">Trở lại</a>
      </div>
    </form>
  </div>
</div>

Areas/Admin/Views/categories/Delete.cshtml
@model Duc_BTL.Areas.Admin.Models.category

@{
    ViewData["Title"] = "Xóa danh mục";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="card mb-4">
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Chỉnh sửa thông tin danh mục</h6>
  </div>
  <div class="card-body">
    <form asp-controller="categories" asp-action="delete">
      <div class="form-group row">
        <label class="col-sm-1 col-form-label">ID</label>
        <div class="col-sm-3">
          <input type="text" class="form-control" placeholder="ID" asp-for="Id" readonly>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label">Name</label>
        <div class="col-sm-3">
          <input type="text" class="form-control" placeholder="ID" asp-for="Name" readonly>
        </div>
      </div>
      <button type="submit" class="btn btn-outline-primary mr-2">Xóa</button>
      <a href="/admin/categories" class="btn btn-outline-danger">Trở lại</a>
    </form>
  </div>
</div>

Areas/Admin/Views/categories/Details.cshtml
@model Duc_BTL.Areas.Admin.Models.category

@{
    ViewData["Title"] = "Thông tin danh mục";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="card mb-4">
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Chi tiết danh mục</h6>
  </div>
  <div class="card-body">
    <form>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label">ID</label>
        <div class="col-sm-3">
          <input type="text" class="form-control" placeholder="ID" asp-for="Id" readonly>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label">Name</label>
        <div class="col-sm-3">
          <input type="text" class="form-control" placeholder="ID" asp-for="Name">
        </div>
      </div>
      <a href="/admin/categories/edit?id=@Model.Id" class="btn btn-outline-primary">Sửa</a>
      <a href="/admin/categories" class="btn btn-outline-danger">Trở lại</a>
    </form>
  </div>
</div>

Areas/Admin/Views/categories/Edit.cshtml
@model Duc_BTL.Areas.Admin.Models.category

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="card mb-4">
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Chỉnh sửa thông tin danh mục</h6>
  </div>
  <div class="card-body">
    <form asp-controller="categories" asp-action="edit">
      <div class="form-group row">
        <label class="col-sm-1 col-form-label">ID</label>
        <div class="col-sm-3">
          <input type="text" class="form-control" placeholder="ID" asp-for="Id" readonly>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label">Name</label>
        <div class="col-sm-3">
          <input type="text" class="form-control" placeholder="ID" asp-for="Name">
        </div>
      </div>
      <button type="submit" class="btn btn-outline-primary mr-2">Lưu</button>
      <a href="/admin/categories" class="btn btn-outline-danger">Trở lại</a>
    </form>
  </div>
</div>

Areas/Admin/Views/categories/Index.cshtml
@model IEnumerable<Duc_BTL.Areas.Admin.Models.category>

@{
    ViewData["Title"] = "Danh sách danh mục";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
  <div class="col-lg-9 mb-4">
    <!-- Simple Tables -->
    <div class="card">
      <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Danh sách danh mục</h6>
      </div>
      <div class="table-responsive">
        <table class="table align-items-center table-flush">
          <thead class="thead-light">
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>#</th>
            </tr>
          </thead>
          <tbody>
            @foreach (var item in Model)
            {
              <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>
                  <a href="/admin/categories/edit?id=@item.Id" class="btn btn-outline-primary">Sửa</a>
                  <a href="/admin/categories/details?id=@item.Id" class="btn btn-outline-info">Chi tiết</a>
                  <a href="/admin/categories/delete?id=@item.Id" class="btn btn-outline-danger">Xóa</a>
                 </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<a href="/admin/categories/create" class="btn btn-outline-primary mb-5">Thêm mới</a>